# Generated by Django 5.2.7 on 2025-10-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_product_images_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='images',
        ),
    ]
