# Generated by Django 5.2.7 on 2025-10-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
