# Generated by Django 5.2.7 on 2025-10-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_image_productimage_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='images',
            new_name='image',
        ),
    ]
